//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacingClient.RacingDriverServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeamInfo", Namespace="http://schemas.datacontract.org/2004/07/RacingDriverService")]
    [System.SerializableAttribute()]
    public partial class TeamInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BestDriverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BestDriver {
            get {
                return this.BestDriverField;
            }
            set {
                if ((object.ReferenceEquals(this.BestDriverField, value) != true)) {
                    this.BestDriverField = value;
                    this.RaisePropertyChanged("BestDriver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RacingDriverServiceRef.IRacingService")]
    public interface IRacingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRacingService/GetTime", ReplyAction="http://tempuri.org/IRacingService/GetTimeResponse")]
        string GetTime(string team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRacingService/GetTime", ReplyAction="http://tempuri.org/IRacingService/GetTimeResponse")]
        System.Threading.Tasks.Task<string> GetTimeAsync(string team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRacingService/GetTeamInfo", ReplyAction="http://tempuri.org/IRacingService/GetTeamInfoResponse")]
        RacingClient.RacingDriverServiceRef.TeamInfo GetTeamInfo(string team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRacingService/GetTeamInfo", ReplyAction="http://tempuri.org/IRacingService/GetTeamInfoResponse")]
        System.Threading.Tasks.Task<RacingClient.RacingDriverServiceRef.TeamInfo> GetTeamInfoAsync(string team);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRacingServiceChannel : RacingClient.RacingDriverServiceRef.IRacingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RacingServiceClient : System.ServiceModel.ClientBase<RacingClient.RacingDriverServiceRef.IRacingService>, RacingClient.RacingDriverServiceRef.IRacingService {
        
        public RacingServiceClient() {
        }
        
        public RacingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RacingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RacingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RacingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetTime(string team) {
            return base.Channel.GetTime(team);
        }
        
        public System.Threading.Tasks.Task<string> GetTimeAsync(string team) {
            return base.Channel.GetTimeAsync(team);
        }
        
        public RacingClient.RacingDriverServiceRef.TeamInfo GetTeamInfo(string team) {
            return base.Channel.GetTeamInfo(team);
        }
        
        public System.Threading.Tasks.Task<RacingClient.RacingDriverServiceRef.TeamInfo> GetTeamInfoAsync(string team) {
            return base.Channel.GetTeamInfoAsync(team);
        }
    }
}
